project:
  type: website
  output-dir: docs

freeze: true

website:
  title: "Tadeas Cely"
  navbar:

    left:
      - text: "Home"
        href: index.qmd
      - text: "Research"
        href: research.qmd
        
    right:
       - text: "{{< iconify bi github size=1.5em title='GitHub' >}}"
         href: https://github.com/tadeascely
         rel: me
       - text: "{{< iconify bi twitter size=1.5em title='Twitter' >}}"
         href: https://x.com/CelyTadeas
         rel: me


format:
  html:
    theme: sandstone
    css: styles.css
    toc: true
    



