project:
  type: website
  output-dir: docs

website:
  title: "Tadeas Cely"
  navbar:
    
    pinned: true

    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
        
    right:
       - text: "{{< iconify bi github size=1.5em title='GitHub' >}}"
         href: https://github.com/tadeascely
         rel: me
       - text: "{{< iconify bi twitter size=1.5em title='Twitter' >}}"
         href: https://x.com/CelyTadeas
         rel: me


format:
  html:
    theme: sandstone
    css: styles.css
    toc: true
    



