---
title: "Academic Service"
---
### Reviewer
*Public Opinion Quarterly, Political Behavior, Network Science*


### Doctoral Workshop in Political Research (2021-2024)

A new format of regular research workshops at Masaryk University takes place twice a term. At these workshops, pre-doctoral and post-doctoral researchers can present their research to colleagues and faculty members. The workshops also include guests from other departments (notably psychology and security studies), providing an interdisciplinary perspective that greatly benefits some researchers.

As of today, there have been **6 such meetings** with **17 paper presentations**. This is a joint activity with my colleague Jakub Jusko and others. I also appreciate the help of numerous faculty members and PhD candidates throughout this seminar.

### Czech Political Science Association (2022-ongoing)

The national organization of Czech Political Scientists is the only organization connecting political science departments across multiple universities. I was nominated and elected as its **Research Secretary** in 2022 for a three-year term, and re-elected in 2024.

The aims of my tenure as Research Secretary include involving more PhD candidates in the Czech political science community, improving communication across departments, and enhancing engagement with our member base. I also manage day-to-day operations (such as communication with the Czech Academy of Sciences) and contribute to organizing the tri-annual congress. Additionally, I initiated a newsletter, a website, and regular activity updates via email.

I am currently co-authoring a report on perceptions of Czech political science, incorporating insights from both academics and a survey of the general public.

### Brno Workshop on Consequences of Political Polarization (12/2024)

Main convenor of a one-day international research workshop featuring 10 presentations by researchers affiliated with top institutions in: *Austria, Czech Republic, Denmark, Italy, Spain, Turkey,* and the *United States*.



