---
title: "Kulturní války v Evropě: Kde se lidé neshodnou na morálních otázkách a proč"
author: "Tadeáš Celý"
date: 2024-11-03
categories: [Nesouhlas, Evropa]
image: "rep1.svg"
---

Pomocí dozníkový dat od 223,099 různých respondentů z let 1990–2017 se zaměřuji na to, jak se liší předmět politického nesouhlasu napříč evropskými zeměmi s důrazem na nesouhlas na ne-ekonomických otázkách, tzv. kulturní války. Teorie postmaterialismu předpokládá, že rozdíly vznikají mezi méně a více rozvinutými zeměmi v důsledku ekonomického nedostatku. Naopak teze o historickém střetu mezi církví a státem se soustředí na konflikty kolem sekularizace veřejného prostoru, které byly výrazné v katolických zemích a téměř chyběly v protestantských. Tyto konflikty, zakořeněné v náboženských kulturách, ovlivňují politická přesvědčení. Spíše než konflikt věřících a nevěřících jde o rozdíly v důrazu, dané historickou rolí katolických a protestantských institucí. Moje výsledky ukazují, že rozdíly skutečně nesledují vzorec na základé ekonomického rozvoje, ale kopíruje náboženské kultury.

### Klíčová zjištění

-   **Veřejné mínění v otázkách morálky** je v katolických zemích více shlukováno do protichůdných táborů než v protestantských zemích, přičemž shlukování napříč otázkami je o *40 % vyšší* a propojení s ideologickými identitami je o *90 % vyšší*.
-   **U ekonomických otázek** je vzorec opačný: v katolických zemích je shlukování ekonomických postojů o *50 % nižší* a propojení s ideologickými identitami o *70 % nižší*.
-   **Mizící rozdíl mezi Východem a Západem**: Ekonomicky rozvinutější země byly v roce 1990 v otázkách morálky o něco více rozděleny než méně rozvinuté země; avšak v roce 2017 jsou tyto země v těchto otázkách o něco méně rozděleny než méně rozvinuté.

**Prosím, otevřete si**:

[Report v plném znění](Report_1.pdf)

K dispozici je také autorská verze tohoto článku (tzv. preprint):

[Preprint](https://osf.io/cu82k)

### Poděkování

Mnoho kolegů poskytlo cenné rady a komentář k tomuto článku, včetně Andrewa Robertse, Markuse Wagnera, Seana Westwooda, Marca Jacoba, Petera Spáče a Jochema Van Noorda. Dřívější verze tohoto článku byly prezentovány na workshopu NORFACE Polarization & Populism, workshopu EUI Political Behavior in CEE Countries a seminářích na Vídeňské univerzitě, Masarykově univerzitě a Univerzitě v Montrealu. Článek byl také diskutován na konferenci MPSA 2024. Na závěr bych rád poděkoval editorovi a anonymním recenzentům za jejich konstruktivní zpětnou vazbu k dřívější verzi manuskriptu.
